import functions
import adminmod
from tkinter import *
import mysql.connector as mys
import tkinter

def registerpage():
    root=Toplevel()
    root.title("Registration Page")
    root.state('zoomed')
    bg=PhotoImage(file="D:/Sumithra_Personal_Folders/Sumithra/Mini Project - Python/bg/Register.png")
    my_label=Label(root, image=bg)
    my_label.place(x=0,y=0, relwidth=1,relheight=1)
    
    intro=Label(root, text="REGISTER",font=("Impact",60), fg='forest green',bg='white')
    intro.place(x=1000, y=650)
    a=Entry(root,width=20,font=('Arial 24',19))
    b=Entry(root,width=20,font=('Arial 24',19))
    c=Entry(root,width=20,font=('Arial 24',19))
    d=Entry(root,width=20,font=('Arial 24',19))
    b1=Label(root, text="Password", font=("Deja Vu Serif",24), fg="white", bg='forest green')
    c1=Label(root, text="Email ID", font=("Deja Vu Serif",24), fg="white", bg='forest green')
    d1=Label(root, text="Mobile No.", font=("Deja Vu Serif",24), fg="white",bg='forest green')
    a1=Label(root, text="User ID", font=("Deja Vu Serif",24), fg="white", bg='forest green')
    a.place(x=380,y=150)
    b.place(x=380,y=200)
    c.place(x=380,y=250)
    d.place(x=380,y=300)
    a1.place(x=220,y=150)
    b1.place(x=220,y=200)
    c1.place(x=220,y=250)
    d1.place(x=220,y=300)
    a.insert(0, "Enter UserID")
    b.insert(0, "Enter Password")
    c.insert(0, "Enter Email ID")
    d.insert(0, "Enter Mobile No.")
    msg=Label(root, text="Sell or Buy?", padx=3,pady=3,font=("Deja Vu Serif",17), fg="white", bg='forest green').place(x=350, y= 450)
    choice=StringVar()
    Radiobutton(root, text="Buyer", variable=choice, value="B", selectcolor="black", padx=3,pady=3,font=("Deja Vu Serif",17), fg="white", bg='forest green').place(x=350,y=500)
    Radiobutton(root, text="Seller", variable=choice, value="S",selectcolor="black",padx=3,pady=3, font=("Deja Vu Serif",17), fg="white", bg='forest green').place(x=350, y=550)
    sub=Button(root, text="SUBMIT",height=2,width=10,bg="DarkSeaGreen2",font=("Helvetica",19),fg="dark green",command=lambda: functions.checkdetails(a.get(),b.get(),c.get(),d.get(),choice.get()))
    sub.place(x=450,y=650)
    mainloop()
    
def loginpage():
    root=Toplevel()
    root.title("Login Page")
    root.state('zoomed')
    bg=PhotoImage(file="D:/Sumithra_Personal_Folders/Sumithra/Mini Project - Python/bg/Login.png")
    my_label=Label(root, image=bg)
    my_label.place(x=0,y=0, relwidth=1,relheight=1)
    intro=Label(root, text="LOGIN",font=("Impact",60), fg='forest green',bg='white')
    intro.place(x=400,y=20)
    a=Entry(root,width=27,font=('Arial 24',21))
    b=Entry(root,width=27,font=('Arial 24',21))
    a.place(x=120,y=300)
    b.place(x=120,y=400)
    a.insert(0, "Enter User ID")
    b.insert(0, "Enter Password")
    sub=Button(root, text="SUBMIT ",height=2,width=10,bg="DarkSeaGreen2",font=("Helvetica",19),fg="dark green",command=lambda: functions.submitdetails(a.get(),b.get()))
    sub.place(x=280,y=500)
    mainloop()
